---
title: "Assignment 2 Final"
author: "Shruti Chanda, Shubham Chaudhary, Aarjav Sanghvi"
date: "10/23/2021"
output: html_document
---


Importing libraries
```{r}
Pack <- c("tidyverse", "lubridate", "magrittr", "ggplotgui", "pROC", "dplyr", "ggplot2", "broom", "rpart", "C50", "ranger", "randomForest", "caret", "lift", "ROCR", "xgboost", "glmnet")

lapply(Pack, library, character.only = TRUE)
```

Importing the updated dataset
```{r}
df <- read_csv("A:/Studies/Data Mining/Datasets_made/df3.csv")
glimpse(df)
```

Manipulating data
```{r}
df[sapply(df, is.character)] <- lapply(df[sapply(df, is.character)],as.factor)
sapply(df,class)
```

Splitting data
```{r}
TRNPROP = 0.5  #proportion of examples in the training sample
nr<-nrow(df)
trnIndex<- sample(1:nr, size = round(TRNPROP * nr), replace=FALSE)
lcdfTrn <- df[trnIndex, ]
lcdfTst <- df[-trnIndex, ]
```

Question 1- XGBoost
```{r}

fdum<-dummyVars(~.,data=df %>% select(-loan_status))
dxlcdf <- predict(fdum, df)

levels(df$loan_status)
dylcdf <- class2ind(df$loan_status, drop2nd = FALSE) 
colcdf <- dylcdf [ , 1]

dxlcdfTrn <- dxlcdf[trnIndex,]
colcdfTrn <- colcdf[trnIndex]
dxlcdfTst <- dxlcdf[-trnIndex,]
colcdfTst <- colcdf[-trnIndex]

dxTrn <- xgb.DMatrix( subset(dxlcdfTrn, select=-c(annRet, actualTerm, actualReturn, total_pymnt)), label=colcdfTrn)
dxTst <- xgb.DMatrix( subset( dxlcdfTst,select=-c(annRet, actualTerm, actualReturn, total_pymnt)), label=colcdfTst)

xgbWatchlist <- list(train = dxTrn, eval = dxTst)

xgbParam <- list (max_depth = 5, eta = 0.01, objective = "binary:logistic",eval_metric="error", eval_metric = "auc")

xgb_lsM1 <- xgb.train( xgbParam, dxTrn, nrounds = 500, xgbWatchlist, early_stopping_rounds = 10 )


xgb_lsM1$best_iteration
 
xpredTrg<-predict(xgb_lsM1, dxTrn) # best_iteration is used
head(xpredTrg)

xgb_lsM1
 
table(pred=as.numeric(xpredTrg>0.5), act=colcdfTrn)

xpredTst<-predict(xgb_lsM1, dxTst)
pred_xgb_lsM1=prediction(xpredTst, lcdfTst$loan_status, label.ordering = c("Fully Paid","Charged Off"))
aucPerf_xgb_lsM1=performance(pred_xgb_lsM1, "tpr", "fpr")
plot(aucPerf_xgb_lsM1)
abline(a=0, b= 1)

xgbParam <- list (max_depth = 3, eta = 0.1, objective = "binary:logistic", eval_metric="error", eval_metric = "auc")

xgb_lscv <- xgb.cv( xgbParam, dxTrn, nrounds = 500, nfold=5, early_stopping_rounds = 10 )

xgb_lscv$best_iteration

best_cvIter <- which.max(xgb_lscv$evaluation_log$test_auc_mean)
xgb_lsbest <- xgb.train( xgbParam, dxTrn, nrounds = xgb_lscv$best_iteration )

xgb.importance(model = xgb_lsbest) %>% view()

xgbParam <- list (max_depth = 4, objective = "binary:logistic", eval_metric="error", eval_metric = "auc")
xgb_lsM1 <- xgb.train( xgbParam, dxTrn, nrounds = 500, xgbWatchlist, early_stopping_rounds = 10, eta=0.01 )

xgbParam <- list (max_depth = 4, objective = "binary:logistic", eval_metric="auc", eval_metric = "error")
xgb_lsM1 <- xgb.train( xgbParam, dxTrn, nrounds = 500, xgbWatchlist, early_stopping_rounds = 10, eta=0.01 )

xgb_lsM1 <- xgb.train( xgbParam, dxTrn, nrounds = 500, xgbWatchlist, early_stopping_rounds = 10, eta=0.5 )

xgbParam1<-list(objective = "binary:logistic", eval_metric="auc", eval_metric = "error")

xgb_lsM1 <- xgb.train( xgbParam1, dxTrn, nrounds = 500, xgbWatchlist, 
early_stopping_rounds = 10, eta=0.1, max_depth=6 )

xgb_lsM1 <- xgb.train( xgbParam1, dxTrn, nrounds = 1000, xgbWatchlist, 
early_stopping_rounds = 10, eta=0.1, max_depth=6, lambda=0.05 )

xgb_lsM1 <- xgb.train( xgbParam1, dxTrn, nrounds = 1000, xgbWatchlist, early_stopping_rounds = 10, eta=0.1, max_depth=6, lambda=0.05, subsample=0.7, colsample_bytree=0.5 )

xgb_lsM1 <- xgb.train( xgbParam1, dxTrn, nrounds = 1000, xgbWatchlist, early_stopping_rounds
= 10, eta=0.01, max_depth=6, subsample=0.7, colsample_bytree=0.5 )

xgbParamGrid <- expand.grid(max_depth = c(2, 5), eta = c(0.001, 0.01, 0.1) )

```

Question 2- GLM model -> LASSO REGRESSION
```{r}
#LASSO REGRESSION
xD<-lcdfTrn %>% select(-loan_status, -actualTerm, -annRet, -actualReturn, -total_pymnt)
yD<- lcdfTrn$actualReturn

glmDefault_cv<- cv.glmnet(data.matrix(xD), lcdfTrn$loan_status, family="binomial")
predDefSc <- predict(glmDefault_cv, data.matrix(lcdfTst %>% select(-loan_status, -actualTerm, -annRet, -actualReturn, -total_pymnt)), s="lambda.1se", type="class")
glmDefault_cv$lambda.min
glmDefault_cv$lambda.1se
tidy(coef(glmDefault_cv, s = glmDefault_cv$lambda.1se))
plot(glmDefault_cv)
plot(glmDefault_cv$glmnet.fit, xvar="lambda")
plot(glmDefault_cv$glmnet.fit)
summary(glmDefault_cv)


yTrn_glm1 <- factor(ifelse(lcdfTrn$loan_status=="Fully Paid",1,0))
xTrn_glm1 <-lcdfTrn %>% select(-c("loan_status","actualTerm","annRet","total_pymnt","actualReturn"))
glm1 <- cv.glmnet(data.matrix(xTrn_glm1), yTrn_glm1, family ="binomial")
plot(glm1)
glm1$lambda.min
glm1$lambda.1se
tidy(coef(glm1, s = glm1$lambda.1se))
which(glm1$lambda == glm1$lambda.1se)
glm1$glmnet.fit$dev.ratio[which(glm1$lambda == glm1$lambda.1se) ]
glm1_p_Trn=predict(glm1,data.matrix(xTrn_glm1), s="lambda.1se", type="response" )
pred_glmTrn_auc <- prediction(glm1_p_Trn, lcdfTrn$loan_status, label.ordering = c("Charged Off", "Fully Paid"))
aucPerf_glmTrn <- performance(pred_glmTrn_auc, "auc")
aucPerf_glmTrn@y.values
yTst_glm1 <- factor(ifelse(lcdfTst$loan_status=="Fully Paid",1,0))
xTst_glm1 <-lcdfTst %>% select(-c("loan_status","actualTerm","annRet","total_pymnt","actualReturn"))
glm1_p_Tst=predict(glm1,data.matrix(xTst_glm1), s="lambda.1se", type="response" )
pred_glmTst_auc <- prediction(glm1_p_Tst, lcdfTst$loan_status, label.ordering = c("Charged Off", "Fully Paid"))
aucPerf_glmTst <- performance(pred_glmTst_auc, "auc")
aucPerf_glmTst@y.values
```

Question 2- GLM model -> RIDGE REGRESSION
```{r}
#Ridge Regression
yTrn<-factor(if_else(lcdfTrn$loan_status=="Fully Paid", '1', '0') )
xDTrn<-lcdfTrn%>% select(-loan_status, -actualTerm, -annRet, -actualReturn, -total_pymnt, -issue_d)
glmls_cv_a0<- cv.glmnet(data.matrix(xDTrn), lcdfTrn$loan_status, family="binomial", alpha=0)
plot(glmls_cv_a0)


glm1_ridge <- cv.glmnet(data.matrix(xTrn_glm1), yTrn_glm1, family ="binomial", alpha = 0)
plot(glm1_ridge)
glm1_ridge$lambda.min
glm1_ridge$lambda.1se
tidy(coef(glm1_ridge, s = glm1_ridge$lambda.1se))
which(glm1_ridge$lambda == glm1_ridge$lambda.1se)
glm1_ridge$glmnet.fit$dev.ratio[which(glm1_ridge$lambda == glm1_ridge$lambda.1se) ]
glm1_ridge_p_Trn=predict(glm1_ridge,data.matrix(xTrn_glm1), s="lambda.1se", type="response")
pred_glmTrn_rid_auc <- prediction(glm1_ridge_p_Trn, lcdfTrn$loan_status, label.ordering = c("Charged Off", "Fully Paid"))
aucPerf_glmTrn_rid <- performance(pred_glmTrn_rid_auc, "auc")
aucPerf_glmTrn_rid@y.values

##Testing data


glm1_ridge_p_Tst=predict(glm1_ridge,data.matrix(xTst_glm1), s="lambda.1se", type="response")
pred_glmTst_rid_auc <- prediction(glm1_ridge_p_Tst, lcdfTst$loan_status, label.ordering = c("Charged Off", "Fully Paid"))
aucPerf_glmTst_rid <- performance(pred_glmTst_auc, "auc")
aucPerf_glmTst_rid@y.values
```

Question 2- GLM model -> ELASTIC-NET REGRESSION
```{r}
#Elastic-Net Regression
glmls_cv_a2<- cv.glmnet(data.matrix(xDTrn), lcdfTrn$loan_status, family="binomial", alpha=0.2, type.measure = "deviance")
plot(glmls_cv_a2)
glmls_cv_a2$type.measure

glmls_a5<- glmnet(data.matrix(xDTrn), lcdfTrn$loan_status, family="binomial", alpha=0.5, type.measure = "deviance")
plot(glmls_a5)
```

Random Forest for comparison purposes
```{r}
rfModel_Ret <- ranger(actualReturn ~., data=subset(lcdfTrn, select=-c(annRet, actualTerm, loan_status)), num.trees =200, 
importance='permutation')
rfPredRet_trn<- predict(rfModel_Ret, lcdfTrn)
sqrt(mean( (rfPredRet_trn$predictions - lcdfTrn$actualReturn)^2))
#sqrt(mean( ( (predict(rfModel_Ret, lcdfTst))$predictions - lcdfTst$actualReturn)^2))
plot ( (predict(rfModel_Ret, lcdfTst))$predictions, lcdfTst$actualReturn)
plot ( (predict(rfModel_Ret, lcdfTrn))$predictions, lcdfTrn$actualReturn)
```

Question 3- 
```{r}
xpredTst<-predict(xgb_lsM1, dxTst)
scoreTst_xgb_ls <- lcdfTst %>% select(grade, loan_status, actualReturn, actualTerm, int_rate) %>% mutate(score=xpredTst)
scoreTst_xgb_ls <- scoreTst_xgb_ls %>% mutate(tile=ntile(-score, 10))
scoreTst_xgb_ls %>% group_by(tile) %>% summarise(count=n(), avgSc=mean(score), numDefaults=sum(loan_status=="Charged Off"), 
avgActRet=mean(actualReturn), minRet=min(actualReturn), maxRet=max(actualReturn), avgTer=mean(actualTerm), totA=sum(grade=="A"), totB=sum(grade=="B" ), totC=sum(grade=="C"), totD=sum(grade=="D"), totE=sum(grade=="E"), totF=sum(grade=="F") )
```

question 3- performance by decile
```{r}
#Performance by deciles
predRet_Trn <- lcdfTrn %>% select(grade, loan_status, actualReturn, actualTerm, int_rate) %>% mutate(predRet=(predict(rfModel_Ret, lcdfTrn))$predictions)
predRet_Trn <- predRet_Trn %>% mutate(tile=ntile(-predRet, 10))
predRet_Trn %>% group_by(tile) %>% summarise(count=n(), avgpredRet=mean(predRet), numDefaults=sum(loan_status=="Charged Off"), 
avgActRet=mean(actualReturn), minRet=min(actualReturn), maxRet=max(actualReturn), avgTer=mean(actualTerm), totA=sum(grade=="A"), totB=sum(grade=="B" ), totC=sum(grade=="C"), totD=sum(grade=="D"), totE=sum(grade=="E"), totF=sum(grade=="F") )
```


Question 4- Loan Status
```{r}
##glm model performance for loan status

glm1_pred_Trn<-predict(glm1,data.matrix(xTrn_glm1))
scoreTst_xgb_ls <- lcdfTrn %>% select(grade, loan_status, actualReturn, actualTerm, int_rate) %>% mutate(score=glm1_pred_Trn)
scoreTst_xgb_ls <- scoreTst_xgb_ls %>% mutate(tile=ntile(-score, 10))
scoreTst_xgb_ls %>% group_by(tile) %>% summarise(count=n(), avgSc=mean(score), numDefaults=sum(loan_status=="Charged Off"),avgActRet=mean(actualReturn), minRet=min(actualReturn), maxRet=max(actualReturn), avgTer=mean(actualTerm), totA=sum(grade=="A"),totB=sum(grade=="B" ), totC=sum(grade=="C"), totD=sum(grade=="D"), totE=sum(grade=="E"), totF=sum(grade=="F") )

##return value

xD_ret<- lcdfTrn %>% select(-loan_status, -actualTerm, -annRet, -actualReturn)
glmRet_cv<- cv.glmnet(data.matrix(xD_ret), lcdfTrn$actualReturn, family="gaussian")
predRet_Trn <- lcdfTrn %>% select(grade, loan_status, actualReturn, actualTerm, int_rate) %>% mutate(predRet= predict(glmRet_cv, data.matrix(lcdfTrn %>% select(-loan_status, -actualTerm, -annRet, -actualReturn)),s="lambda.min" ) )

predRet_Trn <- predRet_Trn %>% mutate(tile=ntile(-predRet, 10))
predRet_Trn %>% group_by(tile) %>% summarise(count=n(), avgpredRet=mean(predRet), numDefaults=sum(loan_status=="Charged Off"),avgActRet=mean(actualReturn), minRet=min(actualReturn), maxRet=max(actualReturn), avgTer=mean(actualTerm), totA=sum(grade=="A"),totB=sum(grade=="B" ), totC=sum(grade=="C"), totD=sum(grade=="D"), totE=sum(grade=="E"), totF=sum(grade=="F") )

#Combining

pRetSc <- predRet_Trn %>% mutate(poScore=scoreTst_xgb_ls$score)
d <- 1
pRet_d <- pRetSc %>% filter(tile<=d)
pRet_d<- pRet_d %>% mutate(tile2=ntile(-poScore, 20))
pRet_d %>% group_by(tile2) %>% summarise(count=n(), avgPredRet=mean(predRet),numDefaults=sum(loan_status=="Charged Off"), avgActRet=mean(actualReturn), avgTer=mean(actualTerm), totA=sum(grade=="A"), totB=sum(grade=="B" ),totC=sum(grade=="C"), totD=sum(grade=="D"), totE=sum(grade=="E"), totF=sum(grade=="F") )
view(pRet_d)

summary(pRet_d)
```

question 5- ntile for glmnet
```{r}
predRet_Trn <- predRet_Trn %>% mutate(tile=ntile(-predRet, 10))
predRet_Trn %>% group_by(tile) %>% summarise(count=n(), avgpredRet=mean(predRet), numDefaults=sum(loan_status=="Charged Off"), 
avgActRet=mean(actualReturn), minRet=min(actualReturn), maxRet=max(actualReturn), avgTer=mean(actualTerm), totA=sum(grade=="A"), 
totB=sum(grade=="B" ), totC=sum(grade=="C"), totD=sum(grade=="D"), totE=sum(grade=="E"), totF=sum(grade=="F") )
```